package lab.pkg6_alessandroreyes;

import com.toedter.calendar.JDateChooser;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        File archivo = new File("./Users.txt");
        Scanner sc = null;
        usuarios = new ArrayList();
        if (archivo.exists()) {
            try {
                sc = new Scanner(archivo);
                sc.useDelimiter(";");
                
                while (sc.hasNext()) {
                    usuarios.add(new Usuario(sc.next(), sc.next(), sc.next(), sc.next()));
                }
            } catch (Exception ex) {
            }
            sc.close();
        }//fin del if
        
        for (int i = 0; i < usuarios.size(); i++) {
            System.out.println(usuarios.get(i).getUsuario() +" "+ usuarios.get(i).getContraseña());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Crearc = new javax.swing.JDialog();
        btn_crear_r = new javax.swing.JButton();
        btn_crearc = new javax.swing.JButton();
        tf_Cnom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_Cusuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dc_Cdate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        tf_Cpass = new javax.swing.JTextField();
        jd_conv = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_conv = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_msj = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_contacts = new javax.swing.JList<>();
        btn_send = new javax.swing.JButton();
        btn_conv_r = new javax.swing.JButton();
        tf_user = new javax.swing.JTextField();
        pf_pw = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_crearC = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        btn_crear_r.setText("Regresar");
        btn_crear_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crear_rMouseClicked(evt);
            }
        });

        btn_crearc.setText("Crear cuenta");
        btn_crearc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearcMouseClicked(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Usuario");

        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setText("Contraseña");

        javax.swing.GroupLayout jd_CrearcLayout = new javax.swing.GroupLayout(jd_Crearc.getContentPane());
        jd_Crearc.getContentPane().setLayout(jd_CrearcLayout);
        jd_CrearcLayout.setHorizontalGroup(
            jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearcLayout.createSequentialGroup()
                .addComponent(btn_crear_r, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_crearc))
            .addGroup(jd_CrearcLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearcLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearcLayout.createSequentialGroup()
                        .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearcLayout.createSequentialGroup()
                                .addComponent(dc_Cdate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addComponent(tf_Cpass, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearcLayout.createSequentialGroup()
                                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_Cnom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Cusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(78, 78, 78))))
        );
        jd_CrearcLayout.setVerticalGroup(
            jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearcLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Cnom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Cusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193)
                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dc_Cdate, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(tf_Cpass))
                .addGap(178, 178, 178)
                .addGroup(jd_CrearcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear_r, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crearc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ta_conv.setColumns(20);
        ta_conv.setRows(5);
        ta_conv.setText("Conversacion:\n");
        jScrollPane1.setViewportView(ta_conv);

        ta_msj.setColumns(20);
        ta_msj.setRows(5);
        jScrollPane2.setViewportView(ta_msj);

        jl_contacts.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_contacts);

        btn_send.setText("Send");

        btn_conv_r.setText("Regresar");

        javax.swing.GroupLayout jd_convLayout = new javax.swing.GroupLayout(jd_conv.getContentPane());
        jd_conv.getContentPane().setLayout(jd_convLayout);
        jd_convLayout.setHorizontalGroup(
            jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_convLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_convLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_convLayout.createSequentialGroup()
                        .addGroup(jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_conv_r, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(54, 54, 54))))
        );
        jd_convLayout.setVerticalGroup(
            jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_convLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_convLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_convLayout.createSequentialGroup()
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_conv_r, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        btn_crearC.setText("Crear cuenta");
        btn_crearC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearCMouseClicked(evt);
            }
        });

        btn_login.setText("Log in");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_crearC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 287, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pf_pw, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addComponent(tf_user))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearcMouseClicked
        Date fe = dc_Cdate.getDate();
        Date now = new Date();
        String date = fe.toString();
        boolean ver = false;
        for (int i = 0; i < usuarios.size(); i++) {
            if(tf_Cusuario.getText().equals(usuarios.get(i).getUsuario())){
                JOptionPane.showMessageDialog(jd_Crearc, "Ese usuario ya existe.");
                tf_Cusuario.setText("");
                ver = false;
                break;
            }else if (!tf_Cusuario.getText().equals(usuarios.get(i).getUsuario()) && i == usuarios.size()-1){
                ver = true;
                break;
            }
        }
        if(usuarios.isEmpty()){
            ver = true;
        }
        if(now.getYear() - fe.getYear() >= 13 && ver){
            usuarios.add(new Usuario(tf_Cnom.getText(), tf_Cusuario.getText(), tf_Cpass.getText(), date));
            try {
                File archivo = new File("./Users.txt");
                FileWriter fw = null;
                BufferedWriter bw = null;
                try {
                    fw = new FileWriter(archivo, false);
                    bw = new BufferedWriter(fw);
                    for (Usuario t : usuarios) {
                        bw.write(t.getNomcC() + ";");
                        bw.write(t.getUsuario() + ";");
                        bw.write(t.getContraseña() + ";");
                        bw.write(t.getNat() + ";");
                    }
                    bw.flush();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(jd_Crearc, "Usuario creado con exito.");
                tf_Cnom.setText("");
                tf_Cpass.setText("");
                tf_Cusuario.setText("");
                dc_Cdate.setDate(new Date());
            } catch (Exception e) {

            }
        }


    }//GEN-LAST:event_btn_crearcMouseClicked

    private void btn_crearCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearCMouseClicked
        this.setVisible(false);
        jd_Crearc.setModal(true);
        jd_Crearc.pack();
        jd_Crearc.setLocationRelativeTo(this);
        jd_Crearc.setVisible(true);
    }//GEN-LAST:event_btn_crearCMouseClicked

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        boolean ver = false;
        for (int i = 0; i < usuarios.size(); i++) {
            if(usuarios.get(i).getUsuario().equals(tf_user.getText()) && 
                    usuarios.get(i).getContraseña().equals(pf_pw.getText())){
                ver = true;
                break;
            }
        }
        if (ver) {
            DefaultListModel modelo = (DefaultListModel) jl_contacts.getModel();
            for (int i = 0; i < usuarios.size(); i++) {
                modelo.addElement(usuarios.get(i).toString());
            }
            jl_contacts.setModel(modelo);

            this.setVisible(false);
            jd_conv.setModal(true);
            jd_conv.pack();
            jd_conv.setLocationRelativeTo(this);
            jd_conv.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta.");
            tf_user.setText("");
            pf_pw.setText("");
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_crear_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crear_rMouseClicked
        jd_Crearc.setModal(false);
        jd_Crearc.setVisible(false);
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_crear_rMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conv_r;
    private javax.swing.JButton btn_crearC;
    private javax.swing.JButton btn_crear_r;
    private javax.swing.JButton btn_crearc;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_send;
    private com.toedter.calendar.JDateChooser dc_Cdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_Crearc;
    private javax.swing.JDialog jd_conv;
    private javax.swing.JList<String> jl_contacts;
    private javax.swing.JPasswordField pf_pw;
    private javax.swing.JTextArea ta_conv;
    private javax.swing.JTextArea ta_msj;
    private javax.swing.JTextField tf_Cnom;
    private javax.swing.JTextField tf_Cpass;
    private javax.swing.JTextField tf_Cusuario;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> usuarios = new ArrayList();
}

